In [1]:
import numpy as np


In [2]:
import pandas as pd

In [3]:
# Array addition example


In [4]:
arr1 = np.array([1, 2, 3])


In [5]:
arr2 = np.array([2, 4, 6])


In [6]:
print(arr1 + arr2)


[3 6 9]


In [7]:
# Broadcasting


In [8]:
print(arr1 + 4)



[5 6 7]


In [9]:
# Reshaping and flattening


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])


In [11]:
reshaped = arr.reshape(3, 4)


In [12]:
print(reshaped)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
flattened = reshaped.flatten()


In [14]:
print(flattened)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [15]:
# Modify flattened array


In [16]:
flattened[0] = 99


In [17]:
print(flattened)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [18]:
flattened = reshaped.flatten()


In [19]:
flattened[0] = 99


In [20]:
print(flattened)


[99  2  3  4  5  6  7  8  9 10 11 12]


In [21]:
print(reshaped)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
arr1 = np.array([1, 2, 3])


In [23]:
arr2 = np.array([2, 3, 4])


In [24]:
print(arr1 + arr2)  # Output: [3 5 7]


[3 5 7]


In [25]:
print(arr1 + 4)     # Output: [5 6 7]

[5 6 7]


In [26]:
arr1 = np.array([1, 2, 3])


In [27]:
arr2 = np.array([[2], [4], [6]])


In [29]:
print(arr1+arr2)

[[3 4 5]
 [5 6 7]
 [7 8 9]]
